Drop table titulo
Drop table MOTIVO
Drop table ALERGIA
ALTER TABLE PACIENTE DROP CONSTRAINT PACIENTE_REPRESENTANTE_fk
DROP TABLE REPRESENTANTE
ALTER TABLE cita DROP CONSTRAINT CITA_PACIENTE_fk
DROP TABLE PACIENTE
ALTER TABLE RECLAMO DROP CONSTRAINT RECLAMO_CITA_fk
DROP TABLE CITA
DROP TABLE MIEMBRO_PERSONAL
ALTER TABLE RECLAMO_EN_DISPUTA DROP CONSTRAINT RECLAMO_EN_DISPUTA_RECLAMO_FK;
DROP TABLE RECLAMO_EN_DISPUTA
ALTER TABLE RECLAMO DROP CONSTRAINT RECLAMO_POLIZA_FK
DROP TABLE RECLAMO
DROP TABLE COBERTURA
ALTER TABLE PERSONA_DE_CONTACTO DROP CONSTRAINT PERSONA_CONTAC_ASEG_FK;
ALTER TABLE ASEGURADORA DROP CONSTRAINT ASEGURADORA_PER_CONT_FK;
DROP TABLE PERSONA_DE_CONTACTO
DROP TABLE ASEGURADORA
DROP TABLE POLIZA
