SELECT MP.CARGO AS CLASE_DE_MIEMBRO,
SUM(CASE WHEN MP.SEXO = 'M' THEN (R.MONTO_RECLAMADO - R.MONTO_DEBITADO) ELSE 0 END) AS RECLAMACIONES_NO_PAGADAS_MASCULINO,
SUM(CASE WHEN MP.SEXO = 'F' THEN (R.MONTO_RECLAMADO - R.MONTO_DEBITADO) ELSE 0 END) AS RECLAMACIONES_NO_PAGADAS_FEMENINO
FROM RECLAMO R
JOIN CITA C 
ON R.CITA_ID = C.ID
JOIN MIEMBRO_PERSONAL MP 
ON C.MIEMBRO_PERSONAL_CEDULA = MP.CEDULA
WHERE R.ESTADO <> 'PAGO'
GROUP BY MP.CARGO;
