SELECT ASEGURADORA.NIT AS COMPAÑIA, A2.NUMERO AS POLIZA, A2.RECLAMOS
FROM
(SELECT A1.NUMERO, POLIZA.ASEGURADORA_NIT, A1.RECLAMOS
FROM
(SELECT POLIZA.NUMERO, COUNT(RECLAMO.CODIGO) AS RECLAMOS
FROM POLIZA
INNER JOIN RECLAMO
ON RECLAMO.POLIZA_NUMERO= POLIZA.NUMERO
GROUP BY POLIZA.NUMERO) A1
INNER JOIN POLIZA
ON POLIZA.NUMERO = A1.NUMERO)A2
INNER JOIN ASEGURADORA 
ON ASEGURADORA.NIT= A2.ASEGURADORA_NIT


