SELECT 
P.NOMBRE AS PACIENTE,
R.NOMBRE AS REPRESENTANTE,
CASE 
WHEN P.REPRESENTANTE_CEDULA = R.CEDULA THEN P.DESCRIPCION_PARENTESCO
ELSE 'NO TIENE RELACION'
END AS PARENTESCO
FROM 
PACIENTE P
LEFT JOIN 
REPRESENTANTE R ON P.REPRESENTANTE_CEDULA = R.CEDULA
